.TH ytsearch 1
.SH NAME
yt \- Terminal YouTube searcher. 
.SH SYNOPSIS
.B ytsearch
[ARGUMENT] [SEARCH TERM]
.SH DESCRIPTION
ytsearch is a simple POSIX shell script that searches Invidious (https://invidious.io) using its API and displays it to standard output. For a script that plays a selected video check out yt (https://github.com/7Games/yt)
.SH OPTIONS
.TP
.BR -i,\ --interact
Lets the user input a number corosponding to the index of a video listed, it then takes that video and prints its full URL to standard output.
.TP
.BR -h,\ --help
Shows the in built help screen then exits.
.SH ENVIRONMENT VARIABLES
.TP
You can either put these either in your .profile / shell rc file or before the command.
.TP
.BR INVIDIOUS_INSTANCE
The Invidious instance used to search using its API. Make sure that the instance has an enabled API. The var must not have a '/' at the end of the URL. DEFAULT: https://invidious.sevengames.xyz
.SH EXAMPLES
.TP
.BR Search\ for\ video:
$ ytsearch POSIX Shell Scripting
.TP
.BR Search\ and\ let\ the\ user\ select\ the\ video:
$ ytsearch --interact Alternative Front Ends
.TP
.BR Change\ Invidious\ Instance:
$ INVIDIOUS_INSTANCE="https://invidious.example.com" ytsearch
.TP
.BR Search\ and\ then\ play\ video.
$ printf "Search: " && read -r input && ytsearch -i "$input" | tee /tmp/search && mpv $(tail -1 /tmp/search) && rm /tmp/search
.SH SEE ALSO
.BR yt (1),
.BR mpv (1),
.BR tee (1),
.BR printf (1),
.BR read (1),
.BR tail (1),
.BR rm (1)
