.TH ytsearch 1
.SH NAME
yt \- Terminal YouTube searcher. 
.SH SYNOPSIS
.B ytsearch
[ARGUMENT] [SEARCH TERM]
.SH DESCRIPTION
ytsearch is a simple POSIX shell script that searches Invidious (https://invidious.io) using its API and displays it to standard output. For a script that plays a selected video check out yt (https://github.com/7Games/yt)
.SH ENVIRONMENT VARIABLES
.TP
You can either put these either in your .profile / shell rc file or before the command.
.TP
.BR INVIDIOUS_INSTANCE
The Invidious instance used to search using its API. Make sure that the instance has an enabled API. The var must not have a '/' at the end of the URL. DEFAULT: https://invidious.sevengames.xyz
.SH EXAMPLES
.TP
.BR Search\ for\ video:
$ ytsearch POSIX Shell Scripting
.TP
.BR Change\ Invidious\ Instance:
$ INVIDIOUS_INSTANCE="https://invidious.example.com" ytsearch
.TP
.BR Search\ and\ then\ play\ video\ using\ fzf.
$ printf "Search: " && read -r input && ytsearch "$input" | fzf | xargs -I % mpv "https://invidious.sevengames.xyz/watch?v=%"
.TP
.BR Search\ and\ then\ play\ video\ using\ dmenu.
$ search=$(printf "" | dmenu -p "Search: "); ytsearch "$search" | dmenu -l 30 -p "Select a video: " | tail -c 12 | xargs -I % mpv "https://invidious.sevengames.xyz/watch?v=%"
.SH SEE ALSO
.BR yt (1)
